spring.application.name=bookstore-management

spring.datasource.url=jdbc:mysql://localhost:3306/bookstore_management
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
